// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PyPosApi.common.database.context;

#nullable disable

namespace PyPosApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PyPosApi.common.database.schemes.ArticlePayments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<float>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdArticleTrusted")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticleTrusted");

                    b.ToTable("ArticlePayments");
                });

            modelBuilder.Entity("PyPosApi.common.database.schemes.ArticleSalesScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<float>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdArticle")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdCliente")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("char(36)");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticle");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdUser");

                    b.ToTable("ArticleSales");
                });

            modelBuilder.Entity("PyPosApi.common.database.schemes.ArticleScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<float>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("CodeBar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Horizontal")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("IdArticleCategory")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdProvider")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdTypeSale")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Shelf")
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Vertical")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdArticleCategory");

                    b.HasIndex("IdProvider");

                    b.HasIndex("IdTypeSale");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("PyPosApi.common.database.schemes.ArticleTrustedScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<float>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdArticle")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdClient")
                        .HasColumnType("char(36)");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.ToTable("ArticleTrusteds");
                });

            modelBuilder.Entity("PyPosApi.common.database.schemes.BoxsCuts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<float>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TypeCut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("BoxsCuts");
                });

            modelBuilder.Entity("PyPosApi.common.database.schemes.CategoryArticleScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("CategoryArticles");
                });

            modelBuilder.Entity("PyPosApi.common.database.schemes.ClientsScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CodePostal")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("INE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("ListBlack")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PyPosApi.common.database.schemes.ProvidersScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("PyPosApi.common.database.schemes.TypeSalesScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("TypeSales");
                });

            modelBuilder.Entity("PyPosApi.common.database.schemes.UserRolScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("UserRolSchemes");
                });

            modelBuilder.Entity("PyPosApi.common.database.schemes.UserScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CodePostal")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("IdUserRolScheme")
                        .HasColumnType("char(36)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("IdUserRolScheme");

                    b.ToTable("UserSchemes");
                });

            modelBuilder.Entity("PyPosApi.common.database.schemes.ArticlePayments", b =>
                {
                    b.HasOne("PyPosApi.common.database.schemes.ArticleTrustedScheme", "ArticleTrustedScheme")
                        .WithMany()
                        .HasForeignKey("IdArticleTrusted")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleTrustedScheme");
                });

            modelBuilder.Entity("PyPosApi.common.database.schemes.ArticleSalesScheme", b =>
                {
                    b.HasOne("PyPosApi.common.database.schemes.ArticleScheme", "ArticleScheme")
                        .WithMany()
                        .HasForeignKey("IdArticle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PyPosApi.common.database.schemes.ClientsScheme", "ClientScheme")
                        .WithMany()
                        .HasForeignKey("IdCliente");

                    b.HasOne("PyPosApi.common.database.schemes.UserScheme", "UserScheme")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleScheme");

                    b.Navigation("ClientScheme");

                    b.Navigation("UserScheme");
                });

            modelBuilder.Entity("PyPosApi.common.database.schemes.ArticleScheme", b =>
                {
                    b.HasOne("PyPosApi.common.database.schemes.CategoryArticleScheme", "CategoryArticleScheme")
                        .WithMany()
                        .HasForeignKey("IdArticleCategory");

                    b.HasOne("PyPosApi.common.database.schemes.ProvidersScheme", "ProvidersScheme")
                        .WithMany()
                        .HasForeignKey("IdProvider");

                    b.HasOne("PyPosApi.common.database.schemes.TypeSalesScheme", "TypeSalesScheme")
                        .WithMany()
                        .HasForeignKey("IdTypeSale");

                    b.Navigation("CategoryArticleScheme");

                    b.Navigation("ProvidersScheme");

                    b.Navigation("TypeSalesScheme");
                });

            modelBuilder.Entity("PyPosApi.common.database.schemes.ArticleTrustedScheme", b =>
                {
                    b.HasOne("PyPosApi.common.database.schemes.ArticleScheme", "ArticleScheme")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PyPosApi.common.database.schemes.ClientsScheme", "ClientsScheme")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleScheme");

                    b.Navigation("ClientsScheme");
                });

            modelBuilder.Entity("PyPosApi.common.database.schemes.BoxsCuts", b =>
                {
                    b.HasOne("PyPosApi.common.database.schemes.UserScheme", "UserScheme")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserScheme");
                });

            modelBuilder.Entity("PyPosApi.common.database.schemes.UserScheme", b =>
                {
                    b.HasOne("PyPosApi.common.database.schemes.UserRolScheme", "UserRolScheme")
                        .WithMany()
                        .HasForeignKey("IdUserRolScheme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRolScheme");
                });
#pragma warning restore 612, 618
        }
    }
}
